// frontend/src/components/LogPanel.svelte
<!-- src/components/LogPanel.svelte -->
<script>
    import { onMount, onDestroy, afterUpdate } from 'svelte';
    import { t } from '../i18n.js';
    import { rawLogs, timezoneStore } from '../lib/stores.js';
    import { fetchBotLogs, fetchLogs } from '../lib/api.js';

    export let botId = null;

    let collapsed = false;
    let logLevelFilter = 'ALL';
    const logLevels = ['ALL', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'];
    const LOG_LINE_LIMIT_OPTIONS = [200, 500, 1000, 2000];
    let autoScroll = true;
    let logOutputElement;
    let logInterval;
    let renderedLogLimit = 1000;
    let hiddenLogCount = 0;
    let panelHeight = 280;
    let isDragging = false;

    const formatTimestamp = (utcString, timeZone) => {
        if (!utcString) return '...';
        try {
            return new Intl.DateTimeFormat('sv-SE', {
                year: 'numeric', month: '2-digit', day: '2-digit',
                hour: '2-digit', minute: '2-digit', second: '2-digit',
                hour12: false, timeZone: timeZone
            }).format(new Date(utcString));
        } catch (e) {
            return utcString.replace('T', ' ').substring(0, 19);
        }
    };

    const timestampRegex = /^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z)/;
    const levelRegex = /\]\s+-\s+(INFO|WARNING|ERROR|CRITICAL)\s+-\s+/;

    $: _rawLogs = $rawLogs;
    $: _timezone = $timezoneStore;
    $: _limit = renderedLogLimit;

    $: parsedLogs = (() => {
        const allLines = (_rawLogs || '').split('\n').filter(line => line.trim() !== '');
        hiddenLogCount = Math.max(0, allLines.length - _limit);
        const visibleLines = hiddenLogCount > 0 ? allLines.slice(-_limit) : allLines;
        return visibleLines.map(line => {
            const tsMatch = line.match(timestampRegex);
            const lvMatch = line.match(levelRegex);
            const originalTimestamp = tsMatch ? tsMatch[1] : null;
            const level = lvMatch ? lvMatch[1] : 'UNKNOWN';
            let messageText = line;
            if (lvMatch) {
                messageText = line.substring(lvMatch.index + lvMatch[0].length);
            } else if (tsMatch) {
                messageText = line.substring(tsMatch[0].length).trim();
            }
            return {
                level, message: messageText,
                originalLine: line,
                formattedTimestamp: originalTimestamp ? formatTimestamp(originalTimestamp, _timezone) : '...'
            };
        });
    })();

    $: filteredLogs = logLevelFilter === 'ALL' ? parsedLogs : parsedLogs.filter(log => log.level === logLevelFilter);

    async function getLogs() {
        try {
            let logsText;
            if (botId) {
                const result = await fetchBotLogs(botId);
                if (Array.isArray(result)) {
                    logsText = result.join('\n');
                } else if (result && typeof result === 'object' && Array.isArray(result.logs)) {
                    logsText = result.logs.join('\n');
                } else if (typeof result === 'string') {
                    logsText = result;
                } else {
                    logsText = '';
                }
            } else {
                logsText = await fetchLogs();
            }
            rawLogs.set(logsText);
        } catch(e) {
            console.error('Log fetch error:', e);
        }
    }

    onMount(() => {
        try {
            const savedLimit = Number(localStorage.getItem('logPanel.maxLines'));
            if (LOG_LINE_LIMIT_OPTIONS.includes(savedLimit)) renderedLogLimit = savedLimit;
            const savedHeight = Number(localStorage.getItem('logPanel.height'));
            if (savedHeight > 100 && savedHeight < 800) panelHeight = savedHeight;
        } catch (e) {}

        getLogs();
        logInterval = setInterval(getLogs, 5000);
    });

    $: if (typeof window !== 'undefined' && LOG_LINE_LIMIT_OPTIONS.includes(renderedLogLimit)) {
        localStorage.setItem('logPanel.maxLines', String(renderedLogLimit));
    }

    onDestroy(() => {
        if (logInterval) clearInterval(logInterval);
    });

    afterUpdate(() => {
        if (logOutputElement && autoScroll) {
            logOutputElement.scrollTop = logOutputElement.scrollHeight;
        }
    });

    function handleDragStart(e) {
        isDragging = true;
        document.addEventListener('mousemove', handleDragMove);
        document.addEventListener('mouseup', handleDragEnd);
        e.preventDefault();
    }

    function handleDragMove(e) {
        if (!isDragging) return;
        const newHeight = window.innerHeight - e.clientY;
        panelHeight = Math.max(120, Math.min(800, newHeight));
    }

    function handleDragEnd() {
        isDragging = false;
        document.removeEventListener('mousemove', handleDragMove);
        document.removeEventListener('mouseup', handleDragEnd);
        localStorage.setItem('logPanel.height', String(panelHeight));
    }
</script>

<div class="log-panel" class:collapsed style="height: {collapsed ? '44px' : panelHeight + 'px'}">
    <div class="log-header">
        <button class="log-collapse-btn" on:click={() => collapsed = !collapsed}>
            <span>{collapsed ? '▸' : '▾'}</span>
            <span>Logs</span>
            {#if botId}
                <span class="log-bot-tag">{botId}</span>
            {/if}
        </button>
        {#if !collapsed}
            <div class="log-controls">
                <div class="log-filter-group">
                    {#each logLevels as level}
                        <button class:active={logLevelFilter === level} on:click={() => { logLevelFilter = level; autoScroll = true; }}>
                            {level}
                        </button>
                    {/each}
                </div>
                <label class="toggle-switch">
                    <input type="checkbox" bind:checked={autoScroll}>
                    <span class="slider"></span>Auto
                </label>
                <label class="line-limit-control">
                    <select value={renderedLogLimit} on:change={(e) => { const n = Number(e.target.value); if (LOG_LINE_LIMIT_OPTIONS.includes(n)) renderedLogLimit = n; }}>
                        {#each LOG_LINE_LIMIT_OPTIONS as option}
                            <option value={option}>{option}</option>
                        {/each}
                    </select>
                </label>
            </div>
        {/if}
    </div>

    {#if !collapsed}
        <!-- svelte-ignore a11y-no-static-element-interactions -->
        <div class="resize-handle" role="separator" aria-orientation="horizontal" on:mousedown={handleDragStart}></div>
        {#if hiddenLogCount > 0}
            <div class="log-limit-note">Showing last {renderedLogLimit} lines ({hiddenLogCount} hidden)</div>
        {/if}
        <div class="log-output-wrapper">
            <pre bind:this={logOutputElement}><code>{#each filteredLogs as log (log.originalLine)}<span class="log-line {log.level}"><span class="timestamp">{log.formattedTimestamp}</span>{log.message}</span>{/each}</code></pre>
        </div>
    {/if}
</div>

<style>
    .log-panel {
        border-top: 1px solid var(--sidebar-border, rgba(140, 167, 193, .12));
        background: var(--log-shell-bg, #1e1e1e);
        display: flex;
        flex-direction: column;
        transition: height .2s ease;
        overflow: hidden;
    }

    .log-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: .35rem .75rem;
        background: rgba(0, 0, 0, .3);
        border-bottom: 1px solid rgba(255, 255, 255, .06);
        flex-shrink: 0;
        min-height: 44px;
        flex-wrap: wrap;
        gap: .35rem;
    }

    .log-collapse-btn {
        background: transparent;
        border: none;
        color: #b8c8da;
        cursor: pointer;
        font-size: .82rem;
        display: flex;
        align-items: center;
        gap: .4rem;
        padding: .3rem .5rem;
        border-radius: 6px;
        box-shadow: none;
        transition: background .18s ease, color .18s ease;
    }

    .log-collapse-btn:hover {
        background: rgba(255, 255, 255, .08);
        color: #e0e6ef;
    }

    .log-panel.collapsed .log-header {
        cursor: pointer;
        background: rgba(0, 0, 0, .25);
        transition: background .18s ease;
        padding: 0;
    }

    .log-panel.collapsed .log-header:hover {
        background: rgba(0, 0, 0, .4);
    }

    .log-panel.collapsed .log-collapse-btn {
        flex: 1;
        padding: 0 .85rem;
        border-radius: 0;
        min-height: 44px;
        justify-content: flex-start;
    }

    .log-bot-tag {
        font-size: .7rem;
        padding: .08rem .35rem;
        border-radius: 4px;
        background: rgba(69, 163, 230, .2);
        color: #88d1ff;
    }

    .log-controls {
        display: flex;
        align-items: center;
        gap: .5rem;
        flex-wrap: wrap;
    }

    .log-filter-group {
        display: flex;
        gap: .15rem;
        background: rgba(148, 163, 184, .1);
        border-radius: 6px;
        padding: .15rem .25rem;
    }

    .log-filter-group button {
        background: transparent;
        color: #90a4ae;
        padding: .15rem .45rem;
        font-size: .72rem;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        box-shadow: none;
    }

    .log-filter-group button.active {
        background: rgba(69, 163, 230, .35);
        color: #88d1ff;
    }

    .toggle-switch {
        display: inline-flex;
        align-items: center;
        gap: .3rem;
        font-size: .75rem;
        color: #90a4ae;
        cursor: pointer;
    }

    .toggle-switch input[type="checkbox"] {
        width: 14px;
        height: 14px;
    }

    .line-limit-control select {
        padding: .15rem .3rem;
        font-size: .72rem;
        background: rgba(148, 163, 184, .1);
        color: #90a4ae;
        border: 1px solid rgba(148, 163, 184, .15);
        border-radius: 4px;
    }

    .resize-handle {
        height: 4px;
        background: rgba(255, 255, 255, .04);
        cursor: ns-resize;
        flex-shrink: 0;
    }

    .resize-handle:hover {
        background: rgba(69, 163, 230, .4);
    }

    .log-limit-note {
        color: #90a4ae;
        font-size: .72rem;
        padding: .15rem .75rem;
        flex-shrink: 0;
    }

    .log-output-wrapper {
        flex: 1;
        overflow: hidden;
    }

    .log-output-wrapper pre {
        height: 100%;
        margin: 0;
        overflow-y: auto;
        padding: .5rem .75rem;
        box-sizing: border-box;
        font-family: 'Fira Code', 'Courier New', monospace;
        font-size: .78rem;
        line-height: 1.6;
        color: #d4d4d4;
        white-space: pre-wrap;
        word-break: break-all;
    }

    .log-output-wrapper pre code {
        display: block;
    }

    .timestamp {
        color: #9e9e9e;
        margin-right: 1em;
    }

    .log-line { display: block; }
    .log-line.INFO { color: #81c784; }
    .log-line.WARNING { color: #ffd54f; }
    .log-line.ERROR { color: #e57373; }
    .log-line.CRITICAL { color: #ff8a65; font-weight: 700; }
    .log-line.UNKNOWN { color: #90a4ae; }

    .log-line:hover {
        background: rgba(255, 255, 255, .04);
    }

    .log-output-wrapper pre::-webkit-scrollbar {
        width: 6px;
    }

    .log-output-wrapper pre::-webkit-scrollbar-thumb {
        background: rgba(148, 163, 184, .25);
        border-radius: 6px;
    }

    .log-output-wrapper pre::-webkit-scrollbar-track {
        background: transparent;
    }

    .log-output-wrapper pre {
        scrollbar-width: thin;
        scrollbar-color: rgba(148, 163, 184, .25) transparent;
    }

    @media (max-width: 900px) {
        .log-header {
            padding: .25rem .5rem;
        }

        .log-collapse-btn {
            font-size: .75rem;
        }

        .log-filter-group button {
            padding: .1rem .35rem;
            font-size: .65rem;
        }

        .log-output-wrapper pre {
            font-size: .7rem;
            padding: .35rem .5rem;
        }

        .log-controls {
            gap: .3rem;
        }
    }

    @media (max-width: 600px) {
        .log-header {
            flex-direction: column;
            align-items: flex-start;
            gap: .25rem;
            padding: .2rem .4rem;
        }

        .log-filter-group {
            flex-wrap: wrap;
        }

        .log-output-wrapper pre {
            font-size: .65rem;
            padding: .25rem .35rem;
        }
    }
</style>

// frontend-vue/src/components/LogPanel.vue
<script setup lang="ts">
/**
 * LogPanel — footer log viewer.
 *
 * Toolbar: level filter button group (6 literals, click forces auto-scroll),
 * max-line select (persisted in `logPanel.maxLines`), auto-scroll switch,
 * pause/refresh/clear. A 6px resize handle at the top drags the panel height
 * (clamped 120–500) and emits `resize` for the layout to persist.
 */
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { NScrollbar, NButton, NSwitch, NEmpty, NSpace, NSelect } from 'naive-ui'
import { useLogsStore, type LogRow } from '@/stores/logs'

const emit = defineEmits<{
  resize: [height: number]
  'resize-end': [height: number]
}>()

const { t } = useI18n()
const logsStore = useLogsStore()

const scrollbarRef = ref<InstanceType<typeof NScrollbar> | null>(null)

type LevelFilter = 'ALL' | LogRow['level']
const LEVEL_FILTERS: LevelFilter[] = ['ALL', 'ERROR', 'WARN', 'INFO', 'DEBUG', 'OTHER']
const MAX_LINE_OPTIONS = [200, 500, 1000, 2000]

/** Level filter state is local to the panel (store stays polling-agnostic). */
const levelFilter = ref<LevelFilter>('ALL')
const maxLineOptions = MAX_LINE_OPTIONS.map((n) => ({ label: String(n), value: n }))

const filteredRows = computed<LogRow[]>(() => {
  if (levelFilter.value === 'ALL') return logsStore.rows
  return logsStore.rows.filter((row) => row.level === levelFilter.value)
})

function setLevelFilter(level: LevelFilter): void {
  levelFilter.value = level
  logsStore.autoScroll = true
  void scrollToBottom()
}

function setMaxLines(n: number): void {
  logsStore.setMaxLines(n)
}

/** Scroll the log container to the bottom when autoScroll is on. */
async function scrollToBottom(): Promise<void> {
  await nextTick()
  const container = scrollbarRef.value
  if (!container) return
  try {
    const el = container.$el?.querySelector('.n-scrollbar-container') as HTMLElement | null
    if (el) el.scrollTop = el.scrollHeight
  } catch {
    // ignore scroll failures
  }
}

watch(
  () => logsStore.rows,
  () => {
    if (logsStore.autoScroll && !logsStore.paused) void scrollToBottom()
  },
  { deep: false },
)

watch(
  () => logsStore.botId,
  () => {
    void scrollToBottom()
  },
)

// --- resize handle (drag up/down, clamp 120–500) ---
let dragging = false
let lastHeight: number | null = null

function onHandlePointerDown(e: PointerEvent): void {
  e.preventDefault()
  dragging = true
  lastHeight = null
  document.body.style.userSelect = 'none'
  document.addEventListener('pointermove', onHandlePointerMove)
  document.addEventListener('pointerup', onHandlePointerUp)
}

function onHandlePointerMove(e: PointerEvent): void {
  if (!dragging) return
  const height = Math.max(120, Math.min(500, window.innerHeight - e.clientY))
  lastHeight = height
  emit('resize', height)
}

function onHandlePointerUp(): void {
  dragging = false
  if (lastHeight !== null) emit('resize-end', lastHeight)
  document.body.style.userSelect = ''
  document.removeEventListener('pointermove', onHandlePointerMove)
  document.removeEventListener('pointerup', onHandlePointerUp)
}

onBeforeUnmount(() => {
  if (dragging) onHandlePointerUp()
})
</script>

<template>
  <div class="log-panel">
    <div
      class="resize-handle"
      role="separator"
      aria-orientation="horizontal"
      @pointerdown="onHandlePointerDown"
    ></div>
    <div class="log-panel-toolbar">
      <span class="log-panel-title">{{ t('logPanel.logs') }}</span>
      <n-space :size="8" align="center">
        <div class="log-filter-group" role="group" aria-label="log level filter">
          <button
            v-for="level in LEVEL_FILTERS"
            :key="level"
            type="button"
            class="log-filter-btn"
            :class="{ active: levelFilter === level }"
            @click="setLevelFilter(level)"
          >
            {{ level }}
          </button>
        </div>
        <n-select
          v-model:value="logsStore.maxLines"
          :options="maxLineOptions"
          size="tiny"
          :style="{ width: '88px' }"
          @update:value="setMaxLines"
        />
        <span class="log-panel-label">{{ t('logPanel.auto') }}</span>
        <n-switch v-model:value="logsStore.autoScroll" size="small" />
        <n-button
          size="tiny"
          :type="logsStore.paused ? 'primary' : 'default'"
          @click="logsStore.paused = !logsStore.paused"
        >
          {{ logsStore.paused ? '▶' : '⏸' }}
        </n-button>
        <n-button size="tiny" @click="logsStore.refresh()">
          ↻
        </n-button>
        <n-button size="tiny" @click="logsStore.clear()">✕</n-button>
      </n-space>
    </div>
    <div v-if="logsStore.error" class="log-panel-error">{{ logsStore.error }}</div>
    <NScrollbar ref="scrollbarRef" class="log-scroll">
      <n-empty v-if="filteredRows.length === 0" size="small" description="—" class="log-empty" />
      <div v-else class="log-lines">
        <div
          v-for="(row, index) in filteredRows"
          :key="index"
          class="log-line"
          :class="`log-${row.level.toLowerCase()}`"
        >
          {{ row.raw }}
        </div>
      </div>
    </NScrollbar>
  </div>
</template>

<style scoped>
.log-panel {
  display: flex;
  flex-direction: column;
  height: 100%;
}

/* Drag strip on top; physically separate from the layout's toggle bar. */
.resize-handle {
  height: 6px;
  flex-shrink: 0;
  cursor: ns-resize;
  background: transparent;
}

.resize-handle::after {
  content: '';
  display: block;
  height: 2px;
  margin: 2px 0;
  background: var(--log-border);
}

.resize-handle:hover::after {
  background: rgba(69, 163, 230, 0.5);
}

.log-panel-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  padding: 6px 12px;
  border-bottom: 1px solid var(--log-border);
}

.log-panel-title {
  font-weight: 600;
  font-size: 13px;
}

.log-filter-group {
  display: flex;
  gap: 2px;
  background: rgba(148, 163, 184, 0.1);
  border-radius: 6px;
  padding: 2px;
}

.log-filter-btn {
  border: none;
  background: transparent;
  color: #90a4ae;
  padding: 2px 6px;
  font-size: 11px;
  border-radius: 4px;
  cursor: pointer;
  transition: background-color 0.15s ease, color 0.15s ease;
}

.log-filter-btn:hover {
  color: #b8c8da;
}

.log-filter-btn.active {
  background: rgba(69, 163, 230, 0.35);
  color: #88d1ff;
}

.log-panel-label {
  font-size: 12px;
  opacity: 0.7;
}

.log-panel-error {
  padding: 4px 12px;
  font-size: 12px;
  color: var(--log-error);
  background: var(--log-error-bg);
}

.log-scroll {
  flex: 1;
  min-height: 0;
}

.log-lines {
  font-family: var(--font-mono);
  font-size: 12px;
  line-height: 1.5;
  padding: 6px 12px;
}

.log-line {
  white-space: pre-wrap;
  word-break: break-all;
}

.log-empty {
  padding-top: 24px;
}

.log-error {
  color: var(--log-error);
}

.log-warn {
  color: var(--log-warn);
}

.log-info {
  color: var(--log-info);
}

.log-debug {
  color: var(--log-debug);
}

.log-other {
  color: var(--log-other);
}
</style>
